CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -g

build:
	$(CC) $(CFLAGS) CoziListeSimpluInlantuite.c -o cozi1
	$(CC) $(CFLAGS) CoziListeDubluInlantuite.c -o cozi2
	$(CC) $(CFLAGS) CoziListeDubluInlantuiteCirculare.c -o cozi3

